# Generated by Django 5.0.6 on 2024-05-21 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('pessoa_contato', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('numero_telefone', models.CharField(max_length=15)),
            ],
        ),
    ]
